#!/bin/bash
################################################################################
# Module 03: Build Tools
# Installs colcon, build optimizers (ccache, ninja, mold), and ROS2 build tools
################################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../common.sh"

log_step "Installing build tools"

# ROS2 build tools + build optimization tools
# - ccache: compiler cache, ~50-80% faster rebuilds
# - ninja-build: faster CMake generator than Make (10-15% faster, better parallelism)
# - mold: high-performance linker, 2-5x faster than GNU ld for shared libraries
log_install "colcon + mixin + ccache + ninja + mold" "apt"
if install_apt_packages \
        python3-colcon-common-extensions \
        python3-colcon-mixin \
        ccache \
        ninja-build \
        mold; then
    log_success "colcon + mixin + ccache + ninja + mold" "installed"
else
    log_fail "colcon + mixin + ccache + ninja + mold" "apt install failed"
    exit 1
fi

# Verify build optimization tools and report status
if command -v ninja &> /dev/null; then
    log_success "ninja" "$(ninja --version) -- build.sh auto-detects and uses Ninja when available"
fi
if command -v mold &> /dev/null; then
    log_success "mold" "$(mold --version 2>&1 | head -1) -- build.sh auto-detects and uses mold for native linking"
fi

# Configure ccache for ROS2 development
# These settings optimize cache hit rates for the Pragati workspace:
# - sloppiness=time_macros,system_headers: avoid cache misses from __TIME__/__DATE__
#   macros and unchanged system headers (ROS2 has many)
# - hash_dir=false: avoid misses when building from different absolute paths
#   (e.g., different developer home dirs or WSL mount points)
# - inode_cache=true: speed up hashing on ext4 by caching inode metadata
# - max_size=8G: accommodate both native x86_64 and cross-compile aarch64 caches
#   in the same default cache directory (~/.cache/ccache)
if command -v ccache &> /dev/null; then
    ccache_conf_dir="${HOME}/.config/ccache"
    mkdir -p "$ccache_conf_dir"
    if [ ! -f "$ccache_conf_dir/ccache.conf" ]; then
        cat > "$ccache_conf_dir/ccache.conf" << 'CCACHE_EOF'
# Pragati ROS2 ccache configuration
# Generated by setup/modules/03_build_tools.sh
# See design rationale in openspec/changes/optimize-build-pipeline/design.md

max_size = 8G
sloppiness = time_macros,system_headers
hash_dir = false
inode_cache = true
CCACHE_EOF
        log_success "ccache config" "created at $ccache_conf_dir/ccache.conf"
    else
        log_success "ccache config" "already exists at $ccache_conf_dir/ccache.conf (not overwritten)"
    fi
fi

# Setup colcon mixins
log_step "Setting up colcon mixins"
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true
colcon mixin update || true
