#!/bin/bash
# Safe Cleanup Plan for yanthra_move
# This script ONLY archives unused files - does NOT touch working code
# Run from: /home/uday/Downloads/pragati_ros2

set -e  # Exit on error

echo "═══════════════════════════════════════════════════════════"
echo "  YANTHRA_MOVE SAFE CLEANUP"
echo "  Archives unused code without affecting compilation"
echo "═══════════════════════════════════════════════════════════"
echo ""

# 1. Create archive directory structure
echo "📁 [1/5] Creating archive directories..."
mkdir -p src/yanthra_move/archive/legacy_implementations
mkdir -p src/yanthra_move/archive/unused_headers
mkdir -p src/yanthra_move/archive/docs
echo "   ✅ Created: src/yanthra_move/archive/"

# 2. Archive legacy source files (NOT compiled)
echo ""
echo "📦 [2/5] Archiving legacy source files..."

# Move yanthra_move_aruco_detect.cpp
if [ -f "src/yanthra_move/src/yanthra_move_aruco_detect.cpp" ]; then
    git mv src/yanthra_move/src/yanthra_move_aruco_detect.cpp \
           src/yanthra_move/archive/legacy_implementations/
    echo "   ✅ Archived: yanthra_move_aruco_detect.cpp (1,086 lines)"
fi

# Move yanthra_move_calibrate.cpp
if [ -f "src/yanthra_move/src/yanthra_move_calibrate.cpp" ]; then
    git mv src/yanthra_move/src/yanthra_move_calibrate.cpp \
           src/yanthra_move/archive/legacy_implementations/
    echo "   ✅ Archived: yanthra_move_calibrate.cpp (909 lines)"
fi

# Move motor_controller_integration.cpp
if [ -f "src/yanthra_move/src/motor_controller_integration.cpp" ]; then
    git mv src/yanthra_move/src/motor_controller_integration.cpp \
           src/yanthra_move/archive/legacy_implementations/
    echo "   ✅ Archived: motor_controller_integration.cpp (421 lines)"
fi

# Move performance_monitor.cpp (optional - ask user)
if [ -f "src/yanthra_move/src/performance_monitor.cpp" ]; then
    echo ""
    read -p "   Archive performance_monitor.cpp? Could be useful as optional node (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git mv src/yanthra_move/src/performance_monitor.cpp \
               src/yanthra_move/archive/legacy_implementations/
        echo "   ✅ Archived: performance_monitor.cpp (259 lines)"
    else
        echo "   ⏭️  Skipped: performance_monitor.cpp (keeping for future use)"
    fi
fi

# 3. Archive unused headers
echo ""
echo "📦 [3/5] Archiving unused headers..."

# Move yanthra_move_clean.h
if [ -f "src/yanthra_move/include/yanthra_move/yanthra_move_clean.h" ]; then
    git mv src/yanthra_move/include/yanthra_move/yanthra_move_clean.h \
           src/yanthra_move/archive/unused_headers/
    echo "   ✅ Archived: yanthra_move_clean.h (149 lines)"
fi

# Move yanthra_move_compatibility.hpp
if [ -f "src/yanthra_move/include/yanthra_move/yanthra_move_compatibility.hpp" ]; then
    git mv src/yanthra_move/include/yanthra_move/yanthra_move_compatibility.hpp \
           src/yanthra_move/archive/unused_headers/
    echo "   ✅ Archived: yanthra_move_compatibility.hpp (53 lines)"
fi

# Move yanthra_move_calibrate.h
if [ -f "src/yanthra_move/include/yanthra_move/yanthra_move_calibrate.h" ]; then
    git mv src/yanthra_move/include/yanthra_move/yanthra_move_calibrate.h \
           src/yanthra_move/archive/unused_headers/
    echo "   ✅ Archived: yanthra_move_calibrate.h (130 lines)"
fi

# Move joint_move_sensor_msgs.h
if [ -f "src/yanthra_move/include/yanthra_move/joint_move_sensor_msgs.h" ]; then
    git mv src/yanthra_move/include/yanthra_move/joint_move_sensor_msgs.h \
           src/yanthra_move/archive/unused_headers/
    echo "   ✅ Archived: joint_move_sensor_msgs.h (250 lines)"
fi

# 4. Delete duplicate launch file (root version)
echo ""
echo "🗑️  [4/5] Removing duplicate launch file..."
if [ -f "src/yanthra_move/pragati_complete.launch.py" ]; then
    git rm src/yanthra_move/pragati_complete.launch.py
    echo "   ✅ Deleted: pragati_complete.launch.py (root - duplicate)"
    echo "   ✅ Keeping: launch/pragati_complete.launch.py (canonical)"
fi

# 5. Clean up build artifacts
echo ""
echo "🧹 [5/5] Removing build artifacts from source tree..."

# Remove centroid.txt (generated by ArUco detection)
if [ -f "src/yanthra_move/src/centroid.txt" ]; then
    git rm src/yanthra_move/src/centroid.txt
    echo "   ✅ Deleted: src/centroid.txt (ArUco output file)"
fi

# Remove outputs directory
if [ -d "src/yanthra_move/src/outputs" ]; then
    git rm -r src/yanthra_move/src/outputs
    echo "   ✅ Deleted: src/outputs/ (debug images)"
fi

# Add to .gitignore
echo ""
echo "📝 Adding artifacts to .gitignore..."
if [ -f "src/yanthra_move/.gitignore" ]; then
    echo "centroid.txt" >> src/yanthra_move/.gitignore
    echo "outputs/" >> src/yanthra_move/.gitignore
    echo "src/*.txt" >> src/yanthra_move/.gitignore
    echo "src/outputs/" >> src/yanthra_move/.gitignore
    git add src/yanthra_move/.gitignore
    echo "   ✅ Updated: .gitignore"
else
    cat > src/yanthra_move/.gitignore <<EOF
# Build artifacts
build/
install/
log/

# Runtime outputs
centroid.txt
outputs/
src/*.txt
src/outputs/

# IDE
.vscode/
.idea/
EOF
    git add src/yanthra_move/.gitignore
    echo "   ✅ Created: .gitignore"
fi

# 6. Create archive README
echo ""
echo "📄 Creating archive documentation..."
cat > src/yanthra_move/archive/README.md <<'EOF'
# Archived Code - yanthra_move

This directory contains legacy code that is **NOT COMPILED** in the current system.

## Why Archived?

These files were part of the ROS1 → ROS2 migration and monolithic architecture refactor (Sept-Nov 2025). They are preserved for reference but are not used in production.

## Contents

### legacy_implementations/
- **yanthra_move_aruco_detect.cpp** (1,086 lines) - Legacy monolithic ArUco + picking implementation
  - Contains ROS1 patterns
  - **DANGER:** Includes `system("sudo poweroff")` calls - DO NOT USE
  - Replaced by: `motion_controller.cpp` (modern, 45-line ArUco integration)

- **yanthra_move_calibrate.cpp** (909 lines) - Legacy joint calibration routines
  - ROS1 calibration procedures
  - May have been replaced by `arm_calibration: true` parameter

- **motor_controller_integration.cpp** (421 lines) - ODrive/MG6010 abstraction layer
  - Superseded by `motor_control_ros2` service architecture
  - No longer needed with service-based design

- **performance_monitor.cpp** (259 lines) - System monitoring node
  - Standalone performance monitoring (CPU, memory, disk)
  - Could be resurrected as optional node if needed

### unused_headers/
- **yanthra_move_clean.h** (149 lines) - Legacy header with multiple include guards
- **yanthra_move_compatibility.hpp** (53 lines) - Compatibility layer for monolithic → modular transition
- **yanthra_move_calibrate.h** (130 lines) - Header for calibrate.cpp
- **joint_move_sensor_msgs.h** (250 lines) - Sensor message utilities

## Current Architecture (Nov 2025)

**Active Code:**
- `motion_controller.cpp` - Modern motion planning with ArUco support ✅
- `yanthra_move_system.cpp` - Modular RAII system (split into 6 files) ✅
- `coordinate_transforms.cpp` - NO-IK direct motor control ✅

**Total Active:** ~4,800 lines  
**Archived:** ~2,800 lines (39% reduction)

## Can These Be Deleted?

**No** - Keep for historical reference and in case functionality needs to be extracted.

**If you need ArUco detection:** It's already working in `motion_controller.cpp:1012-1057`

**If you need calibration:** Check if `arm_calibration: true` parameter works, or extract needed routines.

## Last Updated
November 9, 2025 - Initial archive during code review and cleanup
EOF

git add src/yanthra_move/archive/README.md
echo "   ✅ Created: archive/README.md"

# 7. Summary
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ CLEANUP COMPLETE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📊 Summary:"
echo "   • Archived: 4 legacy source files (~2,675 lines)"
echo "   • Archived: 4 unused headers (~582 lines)"
echo "   • Deleted:  1 duplicate launch file"
echo "   • Deleted:  Build artifacts (centroid.txt, outputs/)"
echo "   • Created:  .gitignore for future artifacts"
echo ""
echo "⚠️  IMPORTANT: Test build before committing!"
echo ""
echo "Next steps:"
echo "   1. cd /home/uday/Downloads/pragati_ros2"
echo "   2. colcon build --packages-select yanthra_move"
echo "   3. colcon test --packages-select yanthra_move"
echo "   4. If tests pass, commit:"
echo "      git commit -m 'Archive unused code - 2,800 lines cleanup'"
echo ""
echo "Total reduction: ~3,257 lines (39% of codebase)"
echo ""
