"""
System log parsers for the log analyzer.

Parses auxiliary log files generated by field_trial_logging.sh:
  - dmesg_network.log   : kernel messages (USB, thermal, OOM, CAN, SPI)
  - network_monitor.log : Ethernet/ping diagnostics from the monitoring loop

These populate EventStore.dmesg_* fields and the NetworkMetrics dataclass
on the analyzer object.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .analyzer import ROS2LogAnalyzer

# ---------------------------------------------------------------------------
# dmesg patterns  (task 15.1)
# ---------------------------------------------------------------------------

_DMESG_PATTERNS = [
    ("usb_disconnect", re.compile(r"USB disconnect|Device disconnected", re.IGNORECASE)),
    ("thermal", re.compile(r"thermal|CPU.*throttl|throttl.*CPU|temperature.*exceeded", re.IGNORECASE)),
    ("oom", re.compile(r"Out of memory|oom.kill|oom-kill|Killed process", re.IGNORECASE)),
    ("can_error", re.compile(r"\bcan[0-9]\b.*error|error.*\bcan[0-9]\b|CAN.*bus.off|bus-off", re.IGNORECASE)),
    ("spi_error", re.compile(r"\bspi[0-9]?\b.*error|error.*\bspi[0-9]?\b|SPI.*timeout", re.IGNORECASE)),
]

# dmesg timestamp: "[  123.456789] " or "2024-01-15T10:23:45.123+0000 kernel: [12345.678]"
_DMESG_TS_PATTERN = re.compile(
    r"(?:^|\s)\[?\s*(\d+\.\d+)\s*\]"   # plain dmesg offset seconds
)
_DMESG_ISO_PATTERN = re.compile(
    r"^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[+-]\d{4}|Z)?)"
)


def _parse_dmesg_timestamp(line: str) -> float | None:
    """Extract a usable epoch float from a dmesg line, best-effort."""
    m = _DMESG_ISO_PATTERN.match(line)
    if m:
        try:
            return datetime.fromisoformat(m.group(1).replace("Z", "+00:00")).timestamp()
        except ValueError:
            pass
    # Fall back to raw offset seconds (not epoch, but keeps ordering)
    m = _DMESG_TS_PATTERN.search(line)
    if m:
        try:
            return float(m.group(1))
        except ValueError:
            pass
    return None


def parse_dmesg_log(analyzer: "ROS2LogAnalyzer", filepath: Path) -> None:
    """
    Parse dmesg_network.log and populate EventStore.dmesg_* lists.

    Silently skips if the file does not exist (arm-role sessions typically
    do not capture dmesg separately).

    Tasks: 15.1
    """
    if not filepath.exists():
        return

    _dest_map = {
        "usb_disconnect": analyzer.events.dmesg_usb_disconnects,
        "thermal": analyzer.events.dmesg_thermal,
        "oom": analyzer.events.dmesg_oom,
        "can_error": analyzer.events.dmesg_can_errors,
        "spi_error": analyzer.events.dmesg_spi_errors,
    }

    try:
        with filepath.open("r", errors="replace") as fh:
            for line in fh:
                line = line.rstrip()
                if not line:
                    continue
                ts = _parse_dmesg_timestamp(line)
                for category, pattern in _DMESG_PATTERNS:
                    if pattern.search(line):
                        _dest_map[category].append({"_ts": ts, "message": line})
                        # a line can match multiple categories (e.g. CAN + USB)
    except OSError:
        pass  # permission errors etc.


# ---------------------------------------------------------------------------
# network_monitor.log parser  (tasks 15.2 – 15.6)
# ---------------------------------------------------------------------------

# Lines look like:
#   2024-01-15 10:23:45  ping_router=12ms  ping_broker=15ms  eth0_state=up  ...
# or
#   2024-01-15 10:23:45  ping_router=timeoutms  ping_broker=selfms  eth0_rx_errors=0 ...
#
# Rules:
#   - Lines starting with '#' are comments — skip
#   - Fields are separated by two or more spaces
#   - Values have 'ms' or 'C' suffix appended directly (no space)
#   - Special values: "timeout" (= packet loss), "self" (= broker on same host, skip),
#     "n/a" (= data unavailable, skip)
#   - Interface name is dynamic: match fields by _state / _rx_errors / _tx_errors / _drops suffix

_NET_TS_PATTERN = re.compile(
    r"^(\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2})"
)
_KV_SPLIT = re.compile(r"\s{2,}")  # two or more spaces = field delimiter


def _strip_unit(value: str) -> str:
    """Remove trailing 'ms' or 'C' unit suffix from a value string."""
    for suffix in ("ms", "C"):
        if value.endswith(suffix):
            return value[: -len(suffix)]
    return value


def _parse_float(raw: str) -> float | None:
    """Strip unit suffix and return float, or None for special/invalid values."""
    stripped = _strip_unit(raw)
    # special sentinel values (after stripping)
    if stripped in ("timeout", "self", "n/a", ""):
        return None
    try:
        return float(stripped)
    except ValueError:
        return None


def _is_timeout(raw: str) -> bool:
    """Return True when the raw value indicates a ping timeout."""
    return _strip_unit(raw) == "timeout"


def _is_self(raw: str) -> bool:
    """Return True when the vehicle itself is the broker (skip this reading)."""
    return _strip_unit(raw) == "self"


def _parse_kv(field: str) -> tuple[str, str] | None:
    """Split 'key=value' into (key, value), or None if malformed."""
    if "=" not in field:
        return None
    key, _, value = field.partition("=")
    return key.strip(), value.strip()


def parse_network_monitor(analyzer: "ROS2LogAnalyzer", filepath: Path) -> None:
    """
    Parse network_monitor.log and populate analyzer.network (NetworkMetrics).

    Format specifics (task 15.3 – 15.5):
      - Skip lines starting with '#'
      - Split on 2+ spaces to get key=value fields
      - Strip 'ms'/'C' unit suffix before interpreting values
      - 'timeout' → count as packet loss, do not add to latency list
      - 'self' → broker is this vehicle, skip that field
      - 'n/a' → unavailable, skip

    Task 15.6: populate NetworkMetrics fields.
    """
    if not filepath.exists():
        return

    net = analyzer.network

    try:
        with filepath.open("r", errors="replace") as fh:
            for raw_line in fh:
                line = raw_line.strip()

                # task 15.3 – skip comments
                if not line or line.startswith("#"):
                    continue

                # Extract timestamp from the beginning of the line
                ts_match = _NET_TS_PATTERN.match(line)
                ts_dt: datetime | None = None
                if ts_match:
                    try:
                        ts_dt = datetime.fromisoformat(ts_match.group(1))
                    except ValueError:
                        pass

                # Split line on 2+ spaces, first token is the timestamp
                parts = _KV_SPLIT.split(line)
                # Skip the leading timestamp token (it's not a key=value pair)
                # We identify key=value pairs by the presence of '='
                for part in parts:
                    kv = _parse_kv(part)
                    if kv is None:
                        continue
                    key, raw_value = kv

                    # --- ping metrics ---
                    if key == "ping_router":
                        if _is_timeout(raw_value):
                            net.ping_router_timeouts += 1
                        elif not _is_self(raw_value):
                            val = _parse_float(raw_value)
                            if val is not None and ts_dt is not None:
                                net.ping_router.append((ts_dt, val))

                    elif key == "ping_broker":
                        if _is_timeout(raw_value):
                            net.ping_broker_timeouts += 1
                        elif not _is_self(raw_value):
                            val = _parse_float(raw_value)
                            if val is not None and ts_dt is not None:
                                net.ping_broker.append((ts_dt, val))

                    # --- CPU temperature ---
                    elif key == "cpu_temp":
                        val = _parse_float(raw_value)
                        if val is not None and ts_dt is not None:
                            net.cpu_temp.append((ts_dt, val))

                    # --- load average ---
                    elif key == "load_avg":
                        val = _parse_float(raw_value)
                        if val is not None and ts_dt is not None:
                            net.load_avg.append((ts_dt, val))

                    # --- dynamic interface fields (task 15.4) ---
                    # Match by suffix: <iface>_state, <iface>_rx_errors, etc.
                    elif key.endswith("_state"):
                        stripped = _strip_unit(raw_value)
                        if stripped not in ("n/a", "self", ""):
                            if ts_dt is not None:
                                net.eth_state_changes.append((ts_dt, stripped))

                    elif key.endswith("_rx_errors"):
                        try:
                            val_int = int(_strip_unit(raw_value))
                            if ts_dt is not None:
                                net.eth_rx_errors.append((ts_dt, val_int))
                        except ValueError:
                            pass

                    elif key.endswith("_tx_errors"):
                        try:
                            val_int = int(_strip_unit(raw_value))
                            if ts_dt is not None:
                                net.eth_tx_errors.append((ts_dt, val_int))
                        except ValueError:
                            pass

                    elif key.endswith("_drops"):
                        try:
                            val_int = int(_strip_unit(raw_value))
                            if ts_dt is not None:
                                net.eth_drops.append((ts_dt, val_int))
                        except ValueError:
                            pass

    except OSError:
        pass
