#!/bin/bash
# Check which steering topics are actually controlling which wheels in Gazebo

echo "========================================================================"
echo "CHECKING TOPIC-TO-WHEEL MAPPING"
echo "========================================================================"
echo ""
echo "Run this test to see which topic controls which physical wheel:"
echo ""
echo "1. Make sure Gazebo and kinematics node are running"
echo ""
echo "2. In a new terminal, publish test angles to each steering topic:"
echo ""
echo "# Test FRONT wheel - publish +45 degrees (0.785 rad)"
echo "ros2 topic pub --once /steering/front std_msgs/msg/Float64 \"data: 0.785\""
echo ""
echo "# Test LEFT wheel - publish +45 degrees"
echo "ros2 topic pub --once /steering/left std_msgs/msg/Float64 \"data: 0.785\""
echo ""
echo "# Test RIGHT wheel - publish +45 degrees"
echo "ros2 topic pub --once /steering/right std_msgs/msg/Float64 \"data: 0.785\""
echo ""
echo "3. Watch in Gazebo - note which PHYSICAL wheel turns for each topic"
echo ""
echo "4. If LEFT topic controls the right-side physical wheel → SWAPPED!"
echo ""
echo "========================================================================"
