#!/bin/bash
# Quick test to verify 3-wheel steering with new configuration

echo "========================================================================"
echo "VEH1 3-WHEEL STEERING TEST"
echo "========================================================================"
echo ""
echo "This tests that ALL wheels now steer (not just front wheel)"
echo ""
echo "NEW CONFIGURATION:"
echo "  Origin: Robot geometric center (not rear axle)"
echo "  Front:  x=+0.755, y=+0.010"
echo "  Left:   x=-0.755, y=+0.910"
echo "  Right:  x=-0.755, y=-0.910"
echo ""
echo "Expected behavior with 'vx=0.4, omega=0.2':"
echo "  Front wheel: ~+21° steering"
echo "  Left wheel:  ~-35° steering (SHOULD STEER NOW!)"
echo "  Right wheel: ~-15° steering (SHOULD STEER NOW!)"
echo ""
echo "========================================================================"
echo "LAUNCH SEQUENCE:"
echo "========================================================================"
echo ""
echo "Terminal 1: Launch Gazebo + robot"
echo "  cd ~/steering\\ control"
echo "  source install/setup.bash"
echo "  ros2 launch veh1 gazebo_with_joy.launch.py use_joystick:=false"
echo ""
echo "Terminal 2: Launch kinematics node"
echo "  cd ~/steering\\ control"
echo "  source install/setup.bash"
echo "  ros2 run veh1 kinematics_node.py"
echo ""
echo "Terminal 3: Launch keyboard control"
echo "  cd ~/steering\\ control"
echo "  source install/setup.bash"
echo "  ros2 run veh1 keyboard_teleop.py"
echo ""
echo "========================================================================"
echo "TEST PROCEDURE:"
echo "========================================================================"
echo ""
echo "1. In Terminal 3 (keyboard), press UP arrow to go forward"
echo "2. While moving forward, press RIGHT arrow to add rotation"
echo "3. WATCH THE LOGS in Terminal 2"
echo "4. You should see:"
echo "   - Front wheel: positive steering angle"
echo "   - Left wheel:  NEGATIVE steering angle (was 0° before!)"
echo "   - Right wheel: NEGATIVE steering angle (was 0° before!)"
echo ""
echo "5. Watch in Gazebo - all 3 wheels should physically rotate!"
echo ""
echo "========================================================================"
