#!/bin/bash
# Daily log cleanup for Pragati ROS2 project
# Generated by setup script

cd "/home/uday/Downloads/pragati_ros2"
"/home/uday/Downloads/pragati_ros2/scripts/monitoring/clean_logs.sh" clean --force --days 7 --size 100 >> "/home/uday/Downloads/pragati_ros2/logs/cleanup_reports/daily_cleanup.log" 2>&1
